// Generated by tools/gen_assets.py -- do not edit.
#pragma once

#include <stdint.h>

// Sprite sheet entry. w/h are the strip's size on the 168x144 design
// canvas; (px, py) is its top-left in the (pre-rotated) sheet bitmap,
// where it occupies h columns by w rows. The strip starts ox columns
// from the pen position and the pen then moves adv columns. Ink spans
// [pen + lsb, pen + adv - rsb).
typedef struct {
  uint16_t py;
  uint8_t px;
  uint8_t w;
  uint8_t h;
  int8_t ox;
  uint8_t adv;
  int8_t lsb;
  int8_t rsb;
} SheetEntry;

#define ASSET_SPACE_ADVANCE 4
#define ASSET_AMPM_TRACKING 2

// digits.png
#define ASSET_DIGIT_BAND_H 9
#define ASSET_DIGIT_CAP_OFFSET 0  // rows from band top to cap top
enum {
  DIGIT_0 = 0,
  DIGIT_1 = 1,
  DIGIT_2 = 2,
  DIGIT_3 = 3,
  DIGIT_4 = 4,
  DIGIT_5 = 5,
  DIGIT_6 = 6,
  DIGIT_7 = 7,
  DIGIT_8 = 8,
  DIGIT_9 = 9,
  DIGIT_COLON = 10,
  DIGIT_SLASH = 11,
  DIGIT_MINUS = 12,
  DIGIT_COUNT
};

// weekdays.png
#define ASSET_WDAY_BAND_H 9
#define ASSET_WDAY_CAP_OFFSET 0  // rows from band top to cap top
enum {
  WDAY_SU = 0,
  WDAY_MO = 1,
  WDAY_TU = 2,
  WDAY_WE = 3,
  WDAY_TH = 4,
  WDAY_FR = 5,
  WDAY_SA = 6,
  WDAY_COUNT
};

// words.png
#define ASSET_WORD_BAND_H 12
#define ASSET_WORD_CAP_OFFSET 0  // rows from band top to cap top
enum {
  WORD_ONE = 0,
  WORD_TWO = 1,
  WORD_THREE = 2,
  WORD_FOUR = 3,
  WORD_FIVE = 4,
  WORD_SIX = 5,
  WORD_SEVEN = 6,
  WORD_EIGHT = 7,
  WORD_NINE = 8,
  WORD_TEN = 9,
  WORD_ELEVEN = 10,
  WORD_TWELVE = 11,
  WORD_THIRTEEN = 12,
  WORD_FOURTEEN = 13,
  WORD_FIFTEEN = 14,
  WORD_SIXTEEN = 15,
  WORD_SEVENTEEN = 16,
  WORD_EIGHTEEN = 17,
  WORD_NINETEEN = 18,
  WORD_TWENTY = 19,
  WORD_THIRTY = 20,
  WORD_FORTY = 21,
  WORD_FIFTY = 22,
  WORD_OH = 23,
  WORD_OCLOCK = 24,
  WORD_AM = 25,
  WORD_PM = 26,
  WORD_COUNT
};

// icons.png
enum {
  ICON_QUIET_OFF = 0,
  ICON_QUIET_ON = 1,
  ICON_BATTERY = 2,
  ICON_COUNT
};

static const SheetEntry ASSET_DIGIT_ENTRIES[DIGIT_COUNT] = {
  {    0, 0,  10,  9,  0,  10,  0,  2 },  // 0
  {   10, 0,   7,  9,  0,   7,  0,  2 },  // 1
  {   17, 0,  10,  9,  0,  10,  0,  2 },  // 2
  {   27, 0,  10,  9,  0,  10,  0,  2 },  // 3
  {   37, 0,  10,  9,  0,  10,  0,  2 },  // 4
  {   47, 0,  10,  9, -1,   9, -1,  2 },  // 5
  {   57, 0,  10,  9,  0,  10,  0,  2 },  // 6
  {   67, 0,  10,  9,  0,  10,  0,  2 },  // 7
  {   77, 0,  10,  9,  0,  10,  0,  2 },  // 8
  {   87, 0,  10,  9,  0,  10,  0,  2 },  // 9
  {   97, 0,   4,  9,  0,   4,  0,  2 },  // :
  {  101, 0,   8,  9,  0,   8,  0,  2 },  // /
  {  109, 0,   8,  9,  0,   8,  1,  2 },  // -
};

static const SheetEntry ASSET_WDAY_ENTRIES[WDAY_COUNT] = {
  {    0, 0,  19,  9,  0,  19,  0,  2 },  // Su
  {   19, 0,  25,  9,  0,  25,  0,  2 },  // Mo
  {   44, 0,  21,  9,  0,  21,  0,  2 },  // Tu
  {   65, 0,  27,  9,  0,  27,  0,  2 },  // We
  {   92, 0,  21,  9,  0,  21,  0,  2 },  // Th
  {  113, 0,  19,  9,  0,  19,  0,  2 },  // Fr
  {  132, 0,  19,  9,  0,  19,  0,  2 },  // Sa
};

static const SheetEntry ASSET_WORD_ENTRIES[WORD_COUNT] = {
  {    0, 0,  32, 12,  0,  32,  0,  2 },  // One
  {   32, 0,  36, 12,  0,  36,  0,  2 },  // Two
  {   68, 0,  51, 12,  0,  51,  0,  2 },  // Three
  {  119, 0,  40, 12,  0,  40,  0,  2 },  // Four
  {  159, 0,  35, 12,  0,  35,  0,  2 },  // Five
  {  194, 0,  25, 12,  0,  25,  0,  2 },  // Six
  {  219, 0,  50, 12,  0,  50,  0,  2 },  // Seven
  {  269, 0,  42, 12,  0,  42,  0,  2 },  // Eight
  {  311, 0,  35, 12,  0,  35,  0,  2 },  // Nine
  {  346, 0,  31, 12,  0,  31,  0,  2 },  // Ten
  {  377, 0,  55, 12,  0,  55,  0,  2 },  // Eleven
  {  432, 0,  61, 12,  0,  61,  0,  2 },  // Twelve
  {  493, 0,  74, 12,  0,  74,  0,  2 },  // Thirteen
  {  567, 0,  78, 12,  0,  78,  0,  2 },  // Fourteen
  {  645, 0,  60, 12,  0,  60,  0,  2 },  // Fifteen
  {  705, 0,  63, 12,  0,  63,  0,  2 },  // Sixteen
  {  768, 0,  88, 12,  0,  88,  0,  2 },  // Seventeen
  {  856, 0,  72, 12,  0,  72,  0,  2 },  // Eighteen
  {  928, 0,  73, 12,  0,  73,  0,  2 },  // Nineteen
  { 1001, 0,  63, 12,  0,  63,  0,  2 },  // Twenty
  { 1064, 0,  54, 12,  0,  54,  0,  2 },  // Thirty
  { 1118, 0,  48, 12,  0,  48,  0,  2 },  // Forty
  { 1166, 0,  40, 12,  0,  40,  0,  2 },  // Fifty
  { 1206, 0,  22, 12,  0,  22,  0,  2 },  // Oh
  { 1228, 0,  61, 12,  0,  61,  0,  2 },  // O'Clock
  { 1289, 0,  28, 12,  0,  28,  0,  2 },  // AM
  { 1317, 0,  26, 12,  0,  26,  0,  2 },  // PM
};

static const SheetEntry ASSET_ICON_ENTRIES[ICON_COUNT] = {
  {    0, 0,  13,  9,  0,  13,  0,  0 },  // QUIET_OFF
  {   13, 0,  13,  9,  0,  13,  0,  0 },  // QUIET_ON
  {   26, 0,  20,  9,  0,  20,  0,  0 },  // BATTERY
};
